files = [ 'stream/*' ]

[meta]
'meta/weaponarchetypes.meta' = 'WEAPON_METADATA_FILE'
'meta/weaponanimations.meta' = 'WEAPON_ANIMATIONS_FILE'
'meta/weapons.meta' = 'WEAPONINFO_FILE'
'meta/pedpersonality.meta' = 'PED_PERSONALITY_FILE'
